### PR TITLE
code update #54

### PR DESCRIPTION
**Pull request by farfromrefug**
-  updated to latest api
-  added support for json string in src
-  support for src from assets folder
-  bug fixes and corrections
-  complete new repo structure with lerna integration

### CODE REVIEW

**Comment by farfromrefug** [comment]
@bradmartin just need to change the package name as this is a PR from my master.

**Comment by bradmartin** [comment]
Tried running the `build` script:

```
> nativescript-lottie@5.0.0 build.plugin.esm /Users/bradmartin/Desktop/nativescript-lottie
> tsc -skipLibCheck --target es2015 --module esnext --removeComments --outDir build/esm && node ./build.esm.js

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/Users/bradmartin/Desktop/nativescript-lottie/build.esm.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```

**Comment by farfromrefug** [comment]
My bad let me clean this up

**Comment by farfromrefug** [comment]
THe PR is closed. can you add me as a contributor? will fix this

**Pull request merged**
