### PR TITLE
{N}3, Angular Support, Update to latest native libraries versions

### PR DESCRIPTION
**Pull request by rhanb**
Update `tns-core-modules` to support NS3
Properties binding done should work under Angular, Vue, {N} Observables etc..
Updated `Podfile` and `include.gradle` to download the latest version of the native library

### CODE REVIEW

**Comment by bradmartin** [comment]
@rhanb - can you fix the package.json conflict?

**Comment by rhanb** [comment]
@bradmartin ,

I'm trying but keep saying to me: (after trying 5 times)

```error
This page is out of date. Start over
```

Remove the second one: 

```
<<<<<<< master
    "debug.android": "npm run preparedemo && cd demo && tns debug android --emulator",
    "preparedemong": "npm run build && cd demo-ng && tns plugin remove nativescript-lottie && tns plugin add ../ && tns install",
    "preparedemo": "npm run build && cd demo && tns plugin remove nativescript-lottie && tns plugin add .. && tns install",
    "setup": "cd demo && npm install && cd .. && npm run build && cd demo && tns plugin add .. && cd ..",
=======
    "debug.android":
      "npm run preparedemo && cd demo && tns debug android --emulator",
    "preparedemo":
      "npm run build && cd demo && tns plugin remove nativescript-lottie && tns plugin add .. && tns install",
    "setup":
      "cd demo && npm install && cd .. && npm run build && cd demo && tns plugin add .. && cd ..",
>>>>>>> master
```

To have:

```
    "debug.android": "npm run preparedemo && cd demo && tns debug android --emulator",
    "preparedemong": "npm run build && cd demo-ng && tns plugin remove nativescript-lottie && tns plugin add ../ && tns install",
    "preparedemo": "npm run build && cd demo && tns plugin remove nativescript-lottie && tns plugin add .. && tns install",
    "setup": "cd demo && npm install && cd .. && npm run build && cd demo && tns plugin add .. && cd ..",
```

**Comment by bradmartin** [comment]
I get the same error 😞

**Comment by bradmartin** [comment]
Maybe close this one, resolve it locally and open a new PR 🤔

**Comment by rhanb** [comment]
When pulling I don't get any conflict - that's maybe why we can't resolve the conflicts they already are somehow

**Pull request closed without merging**
